# CONFIG FILE

# Name of the experiment (a name for the results folder)
experiment_name: Omi-32

# Directory where sequencing data is stored (see README for details)
sequencing_data_dir: /n/desai_lab/users/aphillips/babyYODA/titeseq/full_titeseq_data/seq_data/
cytometry_data_dir: /n/desai_lab/users/aphillips/babyYODA/titeseq/full_titeseq_data/flow_data/

# Metadata files (see README for details)
sample_table_filename: metadata/sample_info_omi-32.tsv
replicate_table_filename: metadata/replicate_info_omi-32.tsv
variant_barcode_table: metadata/variants_barcodes_binary-genos.csv
      
# --------------------------
# Read constant regions and NGS sequencing
# --------------------------

const_reg_1: CAGAAATTGATTTCCGAAGAAGACCTGTAGTAACTTAAGAATTC

const_reg_2: ACCGGTCTGACCTCCTTCTCCCTCTCTTCAGGTCTGCAGTCGACGGTACC

umi_length: 8

row_inline_indices:
    - TACCTGA
    - AGAACCAT
    - ACCGTTGAC
    - GCAAGCTGTT
    - TCGGTGGTACG
    - GTTCAACCGATT
    
col_inline_indices:
    - TTGATCG
    - CATTCTCGAG
    - CCTTAGTACTA
    - AGTGGAATACCT
    - GGTATCA
    - GATGTCCT
    - CTCATCCAG

# --------------------------
# Data processing
# --------------------------



# Debug mode, set to False when running the full experiment
debug_mode: False
max_reads_per_file_if_debugging: 50

# parameters for the sequence parsing
num_substitutions_tolerated_in_inline_idx: 1
num_substitutions_tolerated_per_ten_bp: 1
are_indels_tolerated_in_primers: True

# parameters for the Kd inference
bounds_log10Kd_min: -14
bounds_log10Kd_max: -5
bounds_A_min: 100
bounds_A_max: 1000000
bounds_B_min: 1
bounds_B_max: 100000
min_number_counts: 20

# parameters for the Kd cleanup
sigma_max: 1
r2_min: 0.8
max_log10Kd: 13
min_log10Kd: 5

# The plotting codes often throw bugs so here's a flag to just skip it
do_plots: True
